-- ETOS reference nodes and scenario data only; not confirmed partnerships.
INSERT INTO etos.federation (country_code,country_name,organisation_name,headquarters_city,organisation_type,website,founded_year) VALUES
('DE','Deutschland','Leibniz-Gemeinschaft','Berlin','Forschungsverbund','https://www.leibniz-gemeinschaft.de/',1990),('JP','Japan','Tsukuba Science Network','Tsukuba','Forschungsnetzwerk',NULL,NULL),('US','USA','NASA','Washington','Raumfahrtorganisation','https://www.nasa.gov/',1958),('NO','Norwegen','SINTEF','Trondheim','Forschungsinstitut','https://www.sintef.no/en/',1950),('LU','Luxemburg','LIST','Esch-sur-Alzette','Forschungsinstitut','https://www.list.lu/',2015),('BE','Belgien','imec','Leuven','Technologiezentrum','https://www.imec-int.com/',1984),('ES','Spanien','CSIC','Madrid','Nationaler Forschungsrat','https://www.csic.es/en',1939),('NL','Niederlande','TNO','Den Haag','Innovationsorganisation','https://www.tno.nl/en/',1932),('DK','Dänemark','DTU','Kongens Lyngby','Technische Universität','https://www.dtu.dk/english',1829),('SE','Schweden','KTH','Stockholm','Technische Universität','https://www.kth.se/en',1827) ON CONFLICT (country_code) DO NOTHING;
INSERT INTO etos.research_axis (axis_code,axis_name,description) VALUES
('AI','Künstliche Intelligenz','Maschinelles Lernen und verantwortungsvolle KI.'),('ROBOTICS','Robotik','Autonome, assistive und industrielle Robotik.'),('SPACE','Raumfahrt','Weltraumforschung und Erdbeobachtung.'),('PHOTONICS','Photonik','Lichtbasierte Informations- und Sensortechnologien.'),('METROLOGY','Messtechnik','Messverfahren und Datengüte.'),('KNOWLEDGE','Wissenssysteme','Wissensmodelle und Informationsarchitekturen.'),('EDUCATION','Bildung','Lernsysteme und Wissenschaftskommunikation.'),('SUSTAINABILITY','Nachhaltigkeit','Ressourceneffizienz und resiliente Infrastruktur.'),('HEALTH','Gesundheit','Gesundheitsforschung und Versorgung.'),('DATA','Datenwissenschaft','Datenqualität, Statistik und Governance.') ON CONFLICT (axis_code) DO NOTHING;
INSERT INTO etos.project (project_code,title,project_status,start_date,target_date,description) VALUES
('ETOS-REF-001','Civilian Research Network Model','KONZEPT','2026-01-15',NULL,'Referenzmodell für ein ziviles internationales Forschungsnetzwerk.'),('ETOS-REF-002','Knowledge Systems and Education','PLANUNG','2026-04-01','2027-03-31','Wissenssysteme für Wissenschaft und Bildung.'),('ETOS-REF-003','Photonics and Metrology Exchange','AKTIV','2026-02-01','2026-12-31','Referenzprojekt für Photonik und Messtechnik.'),('ETOS-REF-004','Sustainable Research Infrastructure','AKTIV','2026-03-15','2027-06-30','Nachhaltige Forschungsinfrastrukturen.') ON CONFLICT (project_code) DO NOTHING;
INSERT INTO etos.publication (title,publication_type,publication_status,publication_date,project_id) SELECT 'ETOS 2.0 Civilian Network Model','WHITEPAPER','PLANUNG',NULL,project_id FROM etos.project WHERE project_code='ETOS-REF-001' UNION ALL SELECT 'Wissenssysteme und Bildungsarchitektur','FORSCHUNGSBERICHT','REVIEW',NULL,project_id FROM etos.project WHERE project_code='ETOS-REF-002' UNION ALL SELECT 'Grundlagen der Photonik-Messtechnik','ARTIKEL','VEROEFFENTLICHT','2026-05-20',project_id FROM etos.project WHERE project_code='ETOS-REF-003';
INSERT INTO etos.funding_program (title,sponsor,amount_eur,funding_status,project_id) SELECT 'Concept Development Grant','Internal planning allocation',25000,'BEWILLIGT',project_id FROM etos.project WHERE project_code='ETOS-REF-001' UNION ALL SELECT 'Education Systems Pilot','Reference funding scenario',85000,'BEANTRAGT',project_id FROM etos.project WHERE project_code='ETOS-REF-002' UNION ALL SELECT 'Photonics Methods Programme','Reference funding scenario',140000,'BEWILLIGT',project_id FROM etos.project WHERE project_code='ETOS-REF-003';
